<a href="https://colab.research.google.com/github/atik-bd/MSc-Projects/blob/main/Practical%20Assignment%20%E2%80%93%20Supervised%20Machine%20Learning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Data Preparation

##Data Reading

In [21]:
# Mounting Google Drive as a data source
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [22]:
# Importing the dataset from google drive
from pandas import read_csv,get_dummies,DataFrame
data1=read_csv('/content/drive/MyDrive/DataSets/bank.csv')

In [23]:
# Checking the first five rows of the dataset
data1.head()

,age,job,marital,education,default,balance,housing,loan,contact,day,month,duration,campaign,pdays,previous,poutcome,y
0,30,unemployed,married,primary,no,1787,no,no,cellular,19,oct,79,1,-1,0,unknown,no
1,33,services,married,secondary,no,4789,yes,yes,cellular,11,may,220,1,339,4,failure,no
2,35,management,single,tertiary,no,1350,yes,no,cellular,16,apr,185,1,330,1,failure,no
3,30,management,married,tertiary,no,1476,yes,yes,unknown,3,jun,199,4,-1,0,unknown,no
4,59,blue-collar,married,secondary,no,0,yes,no,unknown,5,may,226,1,-1,0,unknown,no

In [24]:
# Checking the numbers of rows and columns (features) in the dataset
data1.shape

(4521, 17)

In [25]:
# Checking the dataset for number of features and data types
data1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4521 entries, 0 to 4520
Data columns (total 17 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   age        4521 non-null   int64
 1   job        4521 non-null   object
 2   marital    4521 non-null   object
 3   education  4521 non-null   object
 4   default    4521 non-null   object
 5   balance    4521 non-null   int64
 6   housing    4521 non-null   object
 7   loan       4521 non-null   object
 8   contact    4521 non-null   object
 9   day        4521 non-null   int64
 10  month      4521 non-null   object
 11  duration   4521 non-null   int64
 12  campaign   4521 non-null   int64
 13  pdays      4521 non-null   int64
 14  previous   4521 non-null   int64
 15  poutcome   4521 non-null   object
 16  y          4521 non-null   object
dtypes: int64(7), object(10)
memory usage: 600.6+ KB

In [26]:
# Checking the basic statistics for the dataset
data1.describe()

,age,balance,day,duration,campaign,pdays,previous
count,4521.000000,4521.000000,4521.000000,4521.000000,4521.000000,4521.000000,4521.000000
mean,41.170095,1422.657819,15.915284,263.961292,2.793630,39.766645,0.542579
std,10.576211,3009.638142,8.247667,259.856633,3.109807,100.121124,1.693562
min,19.000000,-3313.000000,1.000000,4.000000,1.000000,-1.000000,0.000000
25%,33.000000,69.000000,9.000000,104.000000,1.000000,-1.000000,0.000000
50%,39.000000,444.000000,16.000000,185.000000,2.000000,-1.000000,0.000000
75%,49.000000,1480.000000,21.000000,329.000000,3.000000,-1.000000,0.000000
max,87.000000,71188.000000,31.000000,3025.000000,50.000000,871.000000,25.000000

## Data Encoding

In [27]:
# Binary Encoding_ converting categorical features into numerical binary values
data1['default']=data1['default'].map({'no':1,'yes':0})
data1['housing']=data1['housing'].map({'no':1,'yes':0})
data1['loan']=data1['loan'].map({'no':1,'yes':0})
data1['y']=data1['y'].map({'no':1,'yes':0})
data1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4521 entries, 0 to 4520
Data columns (total 17 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   age        4521 non-null   int64
 1   job        4521 non-null   object
 2   marital    4521 non-null   object
 3   education  4521 non-null   object
 4   default    4521 non-null   int64
 5   balance    4521 non-null   int64
 6   housing    4521 non-null   int64
 7   loan       4521 non-null   int64
 8   contact    4521 non-null   object
 9   day        4521 non-null   int64
 10  month      4521 non-null   object
 11  duration   4521 non-null   int64
 12  campaign   4521 non-null   int64
 13  pdays      4521 non-null   int64
 14  previous   4521 non-null   int64
 15  poutcome   4521 non-null   object
 16  y          4521 non-null   int64
dtypes: int64(11), object(6)
memory usage: 600.6+ KB

In [28]:
# One-Hot Encoding_ converts categorical features into multiple binary columns
# There are no ordinal categorical variables, so using one-hot encoding for remaining features
data2 = get_dummies(data1,columns=['job','marital','education','month','contact','poutcome'],dtype=int)
data2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4521 entries, 0 to 4520
Data columns (total 49 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   age                  4521 non-null   int64
 1   default              4521 non-null   int64
 2   balance              4521 non-null   int64
 3   housing              4521 non-null   int64
 4   loan                 4521 non-null   int64
 5   day                  4521 non-null   int64
 6   duration             4521 non-null   int64
 7   campaign             4521 non-null   int64
 8   pdays                4521 non-null   int64
 9   previous             4521 non-null   int64
 10  y                    4521 non-null   int64
 11  job_admin.           4521 non-null   int64
 12  job_blue-collar      4521 non-null   int64
 13  job_entrepreneur     4521 non-null   int64
 14  job_housemaid        4521 non-null   int64
 15  job_management       4521 non-null   int64
 16  job_retired          4521 non-null   int64
 17  job_self-employed    4521 non-null   int64
 18  job_services         4521 non-null   int64
 19  job_student          4521 non-null   int64
 20  job_technician       4521 non-null   int64
 21  job_unemployed       4521 non-null   int64
 22  job_unknown          4521 non-null   int64
 23  marital_divorced     4521 non-null   int64
 24  marital_married      4521 non-null   int64
 25  marital_single       4521 non-null   int64
 26  education_primary    4521 non-null   int64
 27  education_secondary  4521 non-null   int64
 28  education_tertiary   4521 non-null   int64
 29  education_unknown    4521 non-null   int64
 30  month_apr            4521 non-null   int64
 31  month_aug            4521 non-null   int64
 32  month_dec            4521 non-null   int64
 33  month_feb            4521 non-null   int64
 34  month_jan            4521 non-null   int64
 35  month_jul            4521 non-null   int64
 36  month_jun            4521 non-null   int64
 37  month_mar            4521 non-null   int64
 38  month_may            4521 non-null   int64
 39  month_nov            4521 non-null   int64
 40  month_oct            4521 non-null   int64
 41  month_sep            4521 non-null   int64
 42  contact_cellular     4521 non-null   int64
 43  contact_telephone    4521 non-null   int64
 44  contact_unknown      4521 non-null   int64
 45  poutcome_failure     4521 non-null   int64
 46  poutcome_other       4521 non-null   int64
 47  poutcome_success     4521 non-null   int64
 48  poutcome_unknown     4521 non-null   int64
dtypes: int64(49)
memory usage: 1.7 MB

## Dividing the dataset

In [29]:
X=data2.drop('y',axis=1)
Y=data2['y']
print(X.shape)
print(Y.shape)

(4521, 48)
(4521,)

## Data Scaling

In [30]:
from sklearn.preprocessing import StandardScaler
X_scaled=StandardScaler().fit_transform(X)
DataFrame(X_scaled)

,0,1,2,3,4,5,6,7,8,9,...,38,39,40,41,42,43,44,45,46,47
0,-1.056270,0.130759,0.121072,1.142051,0.424756,0.374052,-0.711861,-0.576829,-0.407218,-0.320413,...,-0.306828,7.450671,-0.107869,0.749079,-0.267071,-0.643536,-0.348652,-0.213447,-0.171381,0.469300
1,-0.772583,0.130759,1.118644,-0.875617,-2.354292,-0.596026,-0.169194,-0.576829,2.989044,2.041734,...,-0.306828,-0.134216,-0.107869,0.749079,-0.267071,-0.643536,2.868193,-0.213447,-0.171381,-2.130831
2,-0.583458,0.130759,-0.024144,-0.875617,0.424756,0.010273,-0.303898,-0.576829,2.899143,0.270124,...,-0.306828,-0.134216,-0.107869,0.749079,-0.267071,-0.643536,2.868193,-0.213447,-0.171381,-2.130831
3,-1.056270,0.130759,0.017726,-0.875617,-2.354292,-1.566105,-0.250017,0.387967,-0.407218,-0.320413,...,-0.306828,-0.134216,-0.107869,-1.334973,-0.267071,1.553915,-0.348652,-0.213447,-0.171381,0.469300
4,1.686036,0.130759,-0.472753,-0.875617,0.424756,-1.323585,-0.146102,-0.576829,-0.407218,-0.320413,...,-0.306828,-0.134216,-0.107869,-1.334973,-0.267071,1.553915,-0.348652,-0.213447,-0.171381,0.469300
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4516,-0.772583,0.130759,-0.583410,-0.875617,0.424756,1.707910,0.250315,0.709566,-0.407218,-0.320413,...,-0.306828,-0.134216,-0.107869,0.749079,-0.267071,-0.643536,-0.348652,-0.213447,-0.171381,0.469300
4517,1.496912,-7.647669,-1.573671,-0.875617,-2.354292,-0.838546,-0.427057,-0.576829,-0.407218,-0.320413,...,-0.306828,-0.134216,-0.107869,-1.334973,-0.267071,1.553915,-0.348652,-0.213447,-0.171381,0.469300
4518,1.496912,0.130759,-0.374724,1.142051,0.424756,0.374052,-0.434754,2.639160,-0.407218,-0.320413,...,-0.306828,-0.134216,-0.107869,0.749079,-0.267071,-0.643536,-0.348652,-0.213447,-0.171381,0.469300
4519,-1.245394,0.130759,-0.094925,1.142051,0.424756,-1.202326,-0.519426,0.387967,1.710451,1.451197,...,-0.306828,-0.134216,-0.107869,0.749079,-0.267071,-0.643536,-0.348652,4.685001,-0.171381,-2.130831
4520,0.267602,0.130759,-0.095257,-0.875617,-2.354292,-1.566105,0.311894,-0.255231,2.090033,3.813344,...,-0.306828,-0.134216,-0.107869,0.749079,-0.267071,-0.643536,-0.348652,4.685001,-0.171381,-2.130831

## Data Splitting

In [31]:
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test=train_test_split(X_scaled,Y,test_size=0.2,random_state=100)
print("X_train:", X_train.shape)
print("X_test:",X_test.shape)
print("Y_train:",Y_train.shape)
print("Y_test:",Y_test.shape)

X_train: (3616, 48)
X_test: (905, 48)
Y_train: (3616,)
Y_test: (905,)

## Data Balancing

In [32]:
Y_train.value_counts()

y
1    3190
0     426
Name: count, dtype: int64

In [33]:
from imblearn.over_sampling import SMOTE
X_train,Y_train=SMOTE(random_state=100).fit_resample(X_train,Y_train)
Y_train.value_counts()

y
1    3190
0    3190
Name: count, dtype: int64

# random forest Using pipeline

## random forest Using pipeline (method #3)

In [98]:
from imblearn.pipeline import Pipeline
from sklearn.model_selection import GridSearchCV
from sklearn import ensemble
RF_classifier = Pipeline([('balancing', SMOTE(random_state = 50)),('classification', ensemble.RandomForestClassifier(criterion='entropy', max_features='sqrt', random_state=100))]) # building classifier
no_trees = {'classification__n_estimators': [230,235,240,245,250,255,260]}
grid_search1 = GridSearchCV(estimator=RF_classifier, param_grid=no_trees, scoring='recall', cv=5)
grid_search1.fit(X_scaled, Y)
best_parameters = grid_search1.best_params_
print(best_parameters)
best_result = grid_search1.best_score_
print(best_result)

{'classification__n_estimators': 245}
0.9592499999999999

In [36]:
# Random Forest Classifier (method 1)
from sklearn import ensemble
RF_classifier1 =ensemble.RandomForestClassifier(n_estimators=245, criterion='entropy', max_features='sqrt', random_state=50)  # building model
RF_classifier1.fit(X_train,Y_train)#training
Y_predRF=RF_classifier1.predict(X_test)# testing

In [38]:
# Evaluation RF
# Accuracy and confusion matrix
from sklearn import metrics
Accuracy=metrics.accuracy_score(Y_test, Y_predRF) # calculating accuaracy
print("Random Forest Classifier\nAccuracy: ", Accuracy) # Is this a good metric??
con_matrix = metrics.confusion_matrix(Y_test, Y_predRF)
print ("confusion_matrix: \n", con_matrix)
recall = metrics.recall_score(Y_test, Y_predRF)
print ("recall: ",recall)
percision=metrics.precision_score(Y_test, Y_predRF)
print("percision: ",percision)
f1=metrics.f1_score(Y_test, Y_predRF)
print('f1= ',f1)

Random Forest Classifier
Accuracy:  0.9005524861878453
confusion_matrix:
 [[ 32  63]
 [ 27 783]]
recall:  0.9666666666666667
percision:  0.925531914893617
f1=  0.9456521739130435

# SVC

##  Support Vector Classifier (method#3)

In [101]:
from imblearn.pipeline import Pipeline
from sklearn import svm
from sklearn.model_selection import GridSearchCV
SV_classifier2 = Pipeline([('balancing', SMOTE(random_state = 100)),('classification', svm.SVC() ) ]) # bulilding classifier
kernels_c = {'classification__kernel': ['linear','poly','rbf','sigmoid'], 'classification__C': [.01,.1,1,10,100]}
grid_search1 = GridSearchCV(estimator=SV_classifier2, param_grid=kernels_c, scoring='recall', cv=5)
grid_search1.fit(X_scaled, Y)
best_parameters = grid_search1.best_params_
print(best_parameters)
best_result = grid_search1.best_score_
print(best_result)

{'classification__C': 0.01, 'classification__kernel': 'poly'}
0.9644999999999999

In [17]:
#building SVM using method#1
from sklearn.svm import SVC
SV_classifier1 = SVC(kernel='poly', C=0.01)  # building classifier
SV_classifier1.fit(X_train, Y_train) # training
Y_predSVC= SV_classifier1.predict(X_test)  #testing

In [39]:
# Evaluation SVC
# Accuracy and confusion matrix
from sklearn import metrics
Accuracy=metrics.accuracy_score(Y_test, Y_predSVC) # calculating accuaracy
print("Support Vector Classifier\nAccuracy: ", Accuracy) # Is this a good metric??
con_matrix = metrics.confusion_matrix(Y_test, Y_predSVC)
print ("confusion_matrix: \n", con_matrix)
recall = metrics.recall_score(Y_test, Y_predSVC)
print ("recall: ",recall)
percision=metrics.precision_score(Y_test, Y_predSVC)
print("percision: ",percision)
f1=metrics.f1_score(Y_test, Y_predSVC)
print('f1= ',f1)

Support Vector Classifier
Accuracy:  0.8983425414364641
confusion_matrix:
 [[ 22  73]
 [ 19 791]]
recall:  0.9765432098765432
percision:  0.9155092592592593
f1=  0.945041816009558